// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // DIRECT_URL: port 5432 session mode — safe for CLI/migrations
    // DATABASE_URL: port 6543 transaction mode — used by app at runtime via adapter
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
